[project]
name = "django-inshard"
version = "0.1"
description = "Hash-based queryset sharding for Django"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Tanner Hobson"}]
license = "Apache-2.0"
classifiers = []
dependencies = [
    "django>=4.2",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-django",
    "psycopg[binary]",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/player1537/django-inshard"
Changelog = "https://github.com/player1537/django-inshard/releases"
Issues = "https://github.com/player1537/django-inshard/issues"
CI = "https://github.com/player1537/django-inshard/actions"
